-- =============================================================================
--  Smart Park - modelo fisico (PostgreSQL 16)
--  V1: as mesmas sete tabelas do script de MySQL, no dialeto do PostgreSQL.
--
--  Por que existem dois scripts. O modelo fisico do projeto de extensao e MySQL,
--  e o script de MySQL (db/migration/mysql) continua sendo a referencia. Este aqui
--  existe porque os servicos que hospedam banco de graca costumam oferecer
--  PostgreSQL, nao MySQL - e sem um banco que persista, toda conta criada e toda
--  avaliacao enviada sumiriam no proximo reinicio.
--
--  As duas versoes descrevem o MESMO modelo. As diferencas sao so de dialeto:
--    AUTO_INCREMENT      -> GENERATED BY DEFAULT AS IDENTITY
--    ENUM('A','B')       -> VARCHAR + CHECK ... IN ('A','B')
--    BIT(1)              -> BOOLEAN
--    DATETIME(6)         -> TIMESTAMP(6)
--    DOUBLE              -> DOUBLE PRECISION
--    COMMENT na coluna   -> COMMENT ON COLUMN
--  Nomes de tabela, de coluna e de constraint sao identicos nos dois, de proposito:
--  assim uma consulta escrita para um banco roda no outro sem edicao.
--
--  Conferencia: subir com spring.jpa.hibernate.ddl-auto=validate so funciona se
--  este script e as entidades JPA descreverem a mesma coisa.
--
--  Regra para mudancas: nunca edite um arquivo ja aplicado. Crie V3__..., e crie
--  o par nos DOIS diretorios, senao os bancos divergem.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Categorias usadas para agrupar e filtrar os pontos no mapa (RF06).
-- O slug e o identificador estavel usado pelo front-end (ex.: "banheiro");
-- o nome pode ser reescrito sem quebrar a interface.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_categoria_poi (
    id    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    slug  VARCHAR(40) NOT NULL,
    nome  VARCHAR(80) NOT NULL,
    icone VARCHAR(40),
    cor   VARCHAR(7),

    CONSTRAINT pk_categoria_poi PRIMARY KEY (id),
    CONSTRAINT uk_categoria_poi_slug UNIQUE (slug)
);

COMMENT ON COLUMN tb_categoria_poi.cor IS 'Cor do marcador em hexadecimal, ex.: #16a34a';

-- -----------------------------------------------------------------------------
-- Visitantes e administradores (RF01, RF02, RNF03).
-- senha_hash guarda SEMPRE o hash BCrypt, nunca a senha: sao 60 caracteres
-- comecando com $2a$. Senha legivel nesta coluna e bug.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_usuario (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR(120) NOT NULL,
    email         VARCHAR(160) NOT NULL,
    senha_hash    VARCHAR(100) NOT NULL,
    tipo_perfil   VARCHAR(20)  NOT NULL,
    data_cadastro TIMESTAMP(6) NOT NULL,
    ultimo_acesso TIMESTAMP(6),

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    -- Faz o papel do ENUM do MySQL: o banco recusa um perfil que a aplicacao
    -- nao conheca, mesmo que a linha entre por fora da API.
    CONSTRAINT ck_usuario_tipo_perfil CHECK (tipo_perfil IN ('VISITANTE', 'ADMINISTRADOR'))
);

COMMENT ON COLUMN tb_usuario.senha_hash IS 'Hash BCrypt, nunca a senha em texto';

-- -----------------------------------------------------------------------------
-- Pontos de interesse do parque: banheiros, quadras, lanchonetes (RF03, RF07).
--
-- A posicao fica em latitude/longitude (graus decimais, WGS84) em vez do tipo
-- espacial POINT. Motivo: o Leaflet consome lat/lon direto e assim o mesmo
-- codigo roda igual em H2, MySQL e PostgreSQL, sem depender de PostGIS.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_ponto_interesse (
    id                 BIGINT           GENERATED BY DEFAULT AS IDENTITY,
    nome               VARCHAR(120)     NOT NULL,
    descricao          VARCHAR(600),
    id_categoria       BIGINT           NOT NULL,
    latitude           DOUBLE PRECISION NOT NULL,
    longitude          DOUBLE PRECISION NOT NULL,
    horario_abertura   TIME(6),
    horario_fechamento TIME(6),
    status_operacional VARCHAR(30)      NOT NULL,
    acessivel          BOOLEAN          NOT NULL,
    foto_url           VARCHAR(400),

    CONSTRAINT pk_ponto_interesse PRIMARY KEY (id),
    CONSTRAINT fk_poi_categoria FOREIGN KEY (id_categoria)
        REFERENCES tb_categoria_poi (id),
    CONSTRAINT ck_poi_status_operacional CHECK (
        status_operacional IN ('EM_FUNCIONAMENTO', 'EM_MANUTENCAO', 'FECHADO'))
);

COMMENT ON COLUMN tb_ponto_interesse.latitude IS 'Graus decimais, WGS84';
COMMENT ON COLUMN tb_ponto_interesse.longitude IS 'Graus decimais, WGS84';
COMMENT ON COLUMN tb_ponto_interesse.horario_abertura IS 'Nulo = sempre aberto';
COMMENT ON COLUMN tb_ponto_interesse.acessivel IS 'Rampa, banheiro adaptado (RF12)';

-- -----------------------------------------------------------------------------
-- Agenda de eventos do parque (RF08).
--
-- id_poi_local e opcional: o evento pode acontecer em um ponto mapeado (e entao
-- aparece no mapa) ou apenas ter o local descrito em texto, como "gramado central".
-- -----------------------------------------------------------------------------
CREATE TABLE tb_evento (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    nome             VARCHAR(150) NOT NULL,
    descricao        VARCHAR(800),
    data_hora_inicio TIMESTAMP(6) NOT NULL,
    data_hora_fim    TIMESTAMP(6),
    local_descritivo VARCHAR(200),
    id_poi_local     BIGINT,
    link_mais_info   VARCHAR(400),

    CONSTRAINT pk_evento PRIMARY KEY (id),
    CONSTRAINT fk_evento_poi FOREIGN KEY (id_poi_local)
        REFERENCES tb_ponto_interesse (id)
);

COMMENT ON COLUMN tb_evento.local_descritivo IS 'Usado quando o evento nao esta em um POI';

-- -----------------------------------------------------------------------------
-- Avaliacoes dos pontos de interesse (RF11).
--
-- A unicidade (id_usuario, id_poi) e regra de negocio: uma avaliacao por pessoa
-- em cada ponto. Sem ela, a media seria distorcida por quem avaliasse varias vezes;
-- reavaliar atualiza a nota anterior.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_avaliacao (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    id_usuario     BIGINT       NOT NULL,
    id_poi         BIGINT       NOT NULL,
    nota           INT          NOT NULL,
    comentario     VARCHAR(600),
    data_avaliacao TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_avaliacao PRIMARY KEY (id),
    CONSTRAINT uk_avaliacao_usuario_poi UNIQUE (id_usuario, id_poi),
    CONSTRAINT fk_avaliacao_usuario FOREIGN KEY (id_usuario)
        REFERENCES tb_usuario (id),
    CONSTRAINT fk_avaliacao_poi FOREIGN KEY (id_poi)
        REFERENCES tb_ponto_interesse (id),
    CONSTRAINT ck_avaliacao_nota CHECK (nota BETWEEN 1 AND 5)
);

COMMENT ON COLUMN tb_avaliacao.nota IS 'De 1 a 5 estrelas';

-- -----------------------------------------------------------------------------
-- Missoes de gamificacao (RF10): desafios diarios e semanais.
-- valor_meta e lido conforme tipo_meta: km para DISTANCIA, quantidade para
-- CHECKIN e EVENTO.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_missao (
    id                BIGINT           GENERATED BY DEFAULT AS IDENTITY,
    nome              VARCHAR(120)     NOT NULL,
    descricao         VARCHAR(400),
    tipo_meta         VARCHAR(20)      NOT NULL,
    periodicidade     VARCHAR(20)      NOT NULL,
    valor_meta        DOUBLE PRECISION NOT NULL,
    pontos_recompensa INT              NOT NULL,

    CONSTRAINT pk_missao PRIMARY KEY (id),
    CONSTRAINT ck_missao_tipo_meta CHECK (tipo_meta IN ('DISTANCIA', 'CHECKIN', 'EVENTO')),
    CONSTRAINT ck_missao_periodicidade CHECK (periodicidade IN ('DIARIA', 'SEMANAL'))
);

COMMENT ON COLUMN tb_missao.valor_meta IS 'km para DISTANCIA, quantidade nos demais';

-- -----------------------------------------------------------------------------
-- Progresso de cada usuario em cada missao (RF10).
-- Uma linha por par (usuario, missao): o avanco e acumulado nela, e ao alcancar
-- valor_meta a missao e marcada como concluida.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_progresso_missao (
    id              BIGINT           GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      BIGINT           NOT NULL,
    id_missao       BIGINT           NOT NULL,
    progresso_atual DOUBLE PRECISION NOT NULL,
    concluida       BOOLEAN          NOT NULL,
    data_conclusao  TIMESTAMP(6),

    CONSTRAINT pk_progresso_missao PRIMARY KEY (id),
    CONSTRAINT uk_progresso_usuario_missao UNIQUE (id_usuario, id_missao),
    CONSTRAINT fk_progresso_usuario FOREIGN KEY (id_usuario)
        REFERENCES tb_usuario (id),
    CONSTRAINT fk_progresso_missao FOREIGN KEY (id_missao)
        REFERENCES tb_missao (id)
);
